version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "url"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"